function GetJCFFocusOptions()
    return {
        order = 3,
        name = "Focus",
        handler = JCFFocusSettings,
        type = "group",
        args = {
            focusEnable = {
                order = 1,
                width = "full",
                name = "Enable",
                desc = "Enable or disable",
                type = "toggle",
                get = "GetEnabled",
                set = "SetEnabled",
            },
            focusClassPortraitEnable = {
                disabled = function() return not JCFFocusSettings:GetEnabled() end,
                order = 2,
                width = "full",
                name = "Class Icon Portrait",
                desc = "Enable or disable class icon portrait",
                type = "toggle",
                get = "GetClassPortraitEnabled",
                set = "SetClassPortraitEnabled",
            },
            focusClassColorHealthEnable = {
                disabled = function() return not JCFFocusSettings:GetEnabled() end,
                order = 3,
                width = "full",
                name = "Class Color Health Bar",
                desc = "Enable or disable class color focus health bar",
                type = "toggle",
                get = "GetClassColorHealthEnabled",
                set = "SetClassColorHealthEnabled",
            },
            focusHideNameBackground = {
                disabled = function() return not JCFFocusSettings:GetEnabled() end,
                order = 4,
                width = "full",
                name = "Hide Name Background",
                desc = "Enable or disable hiding the name background",
                type = "toggle",
                get = "GetHideNameBackground",
                set = "SetHideNameBackground",
            },
            focusEliteMode = {
                disabled = function() return not JCFFocusSettings:GetEnabled() end,
                order = 5,
                name = "Elite Mode (players only)",
                desc = "Select an Elite Mode style",
                values = {
                    [0] = "None",
                    [1] = "Rare",
                    [2] = "Elite",
                    [3] = "Rare Elite"
                },
                type = "select",
                get = "GetEliteMode",
                set = "SetEliteMode",
            },
            focusCastBar = {
                name = "Focus Castbar",
                handler = JCFFocusSettings,
                type = "group",
                args = {
                    focusCastBarScale = {
                        disabled = function() return not JCFFocusSettings:GetEnabled() end,
                        order = 1,
                        name = "Focus Castbar Scale",
                        desc = "Set castbar scale",
                        type = "range",
                        get = "GetCastBarScale",
                        set = "SetCastBarScale",
                        softMax = 3,
                        min = 0
                    },
                    focusCastBarReanchor = {
                        order = 2,
                        width = "full",
                        name = "Reanchor Castbar",
                        disabled = function() return not JCFFocusSettings:GetEnabled() end,
                        desc = "Enable or disable reanchoring of the focus castbar",
                        type = "toggle",
                        get = "GetCastBarReanchor",
                        set = "SetCastBarReanchor",
                    },
                    focusCastBarXOffset = {
                        order = 3,
                        name = "Focus Castbar X offset",
                        desc = "Set castbar X offset",
                        disabled = function() return not JCFFocusSettings:GetEnabled() or not JCFFocusSettings:GetCastBarReanchor() end,
                        type = "range",
                        get = "GetCastBarXOffset",
                        set = "SetCastBarXOffset",
                        min = -1000,
                        max = 1000,
                        softMin = -500,
                        softMax = 500,
                        step = 1,
                    },
                    focusCastBarYOffset = {
                        order = 4,
                        name = "Focus Castbar Y offset",
                        desc = "Set castbar Y offset",
                        disabled = function() return not JCFFocusSettings:GetEnabled() or not JCFFocusSettings:GetCastBarReanchor() end,
                        type = "range",
                        get = "GetCastBarYOffset",
                        set = "SetCastBarYOffset",
                        min = -1000,
                        max = 1000,
                        softMin = -500,
                        softMax = 500,
                        step = 1,
                    },
                }
            },
            focusOfFocus = {
                name = "Target of Focus",
                handler = JCFFocusSettings,
                type = "group",
                args = {
                    focusTotClassPortrait = {
                        order = 1,
                        width = "full",
                        name = "Use Class Icon Portrait",
                        disabled = function() return not JCFFocusSettings:GetEnabled() end,
                        desc = "Enable or disable class icon portrait for target of target",
                        type = "toggle",
                        get = "GetTotClassPortrait",
                        set = "SetTotClassPortrait",
                    },
                    focusTotClassColor = {
                        order = 2,
                        width = "full",
                        name = "Class Color Health Bar",
                        disabled = function() return not JCFFocusSettings:GetEnabled() end,
                        desc = "Enable or disable class colored health bar on focus target",
                        type = "toggle",
                        get = "GetTotClassColor",
                        set = "SetTotClassColor",
                    },
                    focusTotReanchor = {
                        order = 3,
                        width = "full",
                        name = "Reanchor Target of Focus",
                        disabled = function() return not JCFFocusSettings:GetEnabled() end,
                        desc = "Enable or disable reanchoring of the target of focus frame",
                        type = "toggle",
                        get = "GetTotReanchor",
                        set = "SetTotReanchor",
                    },
                    focusTotXOffset = {
                        order = 4,
                        name = "Target of Focus X offset",
                        desc = "Set target of focus X offset",
                        disabled = function() return not JCFFocusSettings:GetEnabled() or not JCFFocusSettings:GetTotReanchor() end,
                        type = "range",
                        get = "GetTotXOffset",
                        set = "SetTotXOffset",
                        min = -1000,
                        max = 1000,
                        softMin = -500,
                        softMax = 500,
                        step = 1,
                    },
                    focusTotYOffset = {
                        order = 5,
                        name = "Target of Focus Y offset",
                        desc = "Set target of focus Y offset",
                        disabled = function() return not JCFFocusSettings:GetEnabled() or not JCFFocusSettings:GetTotReanchor() end,
                        type = "range",
                        get = "GetTotYOffset",
                        set = "SetTotYOffset",
                        min = -1000,
                        max = 1000,
                        softMin = -500,
                        softMax = 500,
                        step = 1,
                    },
                }
            }
        },
    }
end